services:
  frontend:
    build:
      context: ./client
    ports:
      - 3000:80
    restart: always
    depends_on:
      - backend
    networks:
      - mafia-network

  backend:
    build:
      context: ./backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
    ports:
      - 8080:8080
    restart: no
    depends_on:
      - postgres
      - redis
    networks:
      - mafia-network

  postgres:
    image: postgres:18.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    restart: always
    networks:
      - mafia-network

  redis:
    image: redis:8.6
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - mafia-network

volumes:
  postgres_data:
    name: mafia-postgres
  redis_data:
    name: mafia-redis

networks:
  mafia-network:
