services:
  frontend:
    build:
      context: ./client
    container_name: frontend
    ports:
      - 3000:80
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
      - redis-mafia

  postgres:
    image: postgres:18.1
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    restart: unless-stopped

  redis-mafia:
    image: redis:8.6
    container_name: redis-mafia
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
    name: mafia-postgres
  redis_data:
    name: mafia-redis
