line-length = 88
fix = true
src = ['app']
[lint]
extend-select = ["I", "FAST"]
fixable = ["I"]

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[lint.isort]
combine-as-imports = true
length-sort = true
lines-after-imports = 2
known-first-party = ['.\app']
